### ISSUE TITLE
Trying to read Array keys with values which include functions

### ISSUE THREAD

**Issue by jnbn** [bartvanraaij/php-array-reader#9]
Hi,

I'm trying to read the contents of the file, which has

```
'enabled' => env('ADMIN_ENABLED', true),
```

But as you might expect, it's returning undefined. 

Is there a way to reach that key's raw data like string?

Current parser is using `expr` but couldn't see anything to convert that expr object back to string?

**Comment by bartvanraaij** [comment]
Hi, thanks for reaching out!

I didn't think of adding support for function calls.
It can be done with a few small code changes, see https://github.com/bartvanraaij/php-array-reader/pull/10/files

Do you think that would help you?

**Comment by jnbn** [comment]
Look's like it'll. 

Thank you @bartvanraaij

**Comment by bartvanraaij** [comment]
Cool, I've merged that PR.
If you load up version `2.1.0` of php-array-reader, Bob's your uncle :)
